### ISSUE TITLE
 inDesign eksportR-i

### ISSUE THREAD

**Issue by infokujur** [Demokraatialabor/EIA_2019#1]
Mis tulemuse see annab ja kas saame kasutada?

**Comment by taavisaft** [comment]
InDesign lubab eksportida EPUB formaati, mida saab siis omakorda R/i importida. Kas sellel mõtet on, seda peab reaalse InDesign faili peal veel proovima.

**Comment by infokujur** [comment]
Artikli saatsin meilile. Tekstiga tehakse veel tööd, saab lorem ipsumi asemele panna, kui vaja.
Sellest võiks kujundaja teha mvp faili, et saaks ekspordi ära testida.
Pärast saame timmida.

**Comment by infokujur** [comment]
Sellega sai ühele poole.
