### ISSUE TITLE
Viitamissüsteem

### ISSUE THREAD

**Issue by tkutsar** [Demokraatialabor/EIA_2019#11]

**Comment by tkutsar** [comment]
Viitamine töötab, vajab kahte täiendust:

1) Praegu genereerib automaatselt ingliskeelse pealkirja, vaja sellest lahti saada
2) Eestikeelse viitamise puhul tuleb leida sobiv .csl script (või kirjutada see ise), mis defineerib kasutatud allikate nimistu vorminduse.

**Comment by infokujur** [comment]
@tkutsar vaatab eesti juhendile peale ja vaatab, kuidas see erineb praegusest. Siis kui see selge, siis tegutseme edasi.

**Comment by tkutsar** [comment]
Leitud internetitist "Keel ja kirjandus" .csl script, mis võimaldab viiteid vormistada eesti keeles. EIA stiilijuhendiga on aga viidete vormistuses erinevused, mis on küll väiksemad võrreldes ingliskeelsete scriptidega, aga siiski märkimisväärsed. Kaardistasin neist mõned (lõpuni ei viitsinud, aega nõudev töö), lisan pildifailiga.

<img width="926" alt="Screenshot 2019-08-01 at 13 47 03" src="https://user-images.githubusercontent.com/51828472/62287643-0f1f9200-b463-11e9-8103-2f1e1e6435a8.png">

Scripti on võimalik ümber kirjutada, et viia ta vastavusse EIA stiilijuhendiga, aga see eeldab kõikide vajalike erinevuste täpset kaardistamist ja veidi juurde õppimist, seega ka ajakulu lisa.

**Comment by tkutsar** [comment]
Kuna viited ja kasutatud allikad on trükiversiooni jaoks juba niikuinii vastavalt EIA nõuetele vormistatud, ei ole otstarbekas Bookdowni funktsionaalsust allikate loetelu genereerimiseks kasutada ja lihtsam on manuaalselt linkida juba vormistatud allikate loetelule. Saadan juhendi, kuidas vormistada failid nii, et mul neid mugav importida oleks ja panen issue kinni.
