### ISSUE TITLE
Artikkel 2.3 Fig 1 - Kaart

### ISSUE THREAD

**Issue by tkutsar** [Demokraatialabor/EIA_2019#12]

**Comment by infokujur** [comment]
EstGIS-i seltskonnaga vajadusel kontakti, kui Eestipõhisust vaja lahendada ja üldasjades lahendamata.

**Comment by tkutsar** [comment]
* Kaartide joonestamise võimekus olema (tmap package). Vajadusel võib uurida interaktiivseks tegemise võimalusi.

* Legendi pealkirjad hetkel väikesed võrreldes legendiga, millegipärast ei saanud lahendada.
