### ISSUE TITLE
juhtumikastide kujundus

### ISSUE THREAD

**Issue by tkutsar** [Demokraatialabor/EIA_2019#15]
Proovida läbi artikkel 2.3 peal.

**Comment by tkutsar** [comment]
Esimene variant tehtud. Bookdown võimaldab juhtumikasti jaoks sobivat _custom block_ võimalust. Muidu töötab hästi, aga on paari puudusega:

* ei võimalda rohkemat kui ühte pilti ja ka selle vormistamine on keeruline (lihtsasti saab vaid vasakule äärde). Üks meetod sellest mööda minna oleks pildid näiteks kokku kleepida üheks pildiks.

* Pole katsetanud, aga ilmselt ei tööta kasti sees ka viited allikatele ja joonistele

* Värvid valisin praegu ise juhuslikult. Võib disaineriga läbi rääkida ja vajadusel muuta (CVI-st ei leidnud juhtumiskasti näidet).
<img width="915" alt="Screenshot 2019-07-17 at 16 55 43" src="https://user-images.githubusercontent.com/51828472/61381628-00a67780-a8b4-11e9-87d2-a9d7ec1565ee.png">

**Comment by infokujur** [comment]
Anni põrgatab kujundajaga.
@tkutsar vaatab üle viitamise võimalused, sest viiteid on vaja. Kompromiss - ei ole hüperlingina, aga kasti alla ei too.
