### ISSUE TITLE
Jooniste andmefailid

### ISSUE THREAD

**Issue by tkutsar** [Demokraatialabor/EIA_2019#18]
Siia issue alla postitada andmefailide pakid. Näiteks peatükkide kaupa või valmimisjärjekorras.

**Comment by infokujur** [comment]
csv-d ei võta vastu, aga zip-i võtab.










[Downloads.zip](https://github.com/Demokraatialabor/EIA_2019/files/3696116/Downloads.zip)

**Comment by infokujur** [comment]
[Ports nr 2.zip](https://github.com/Demokraatialabor/EIA_2019/files/3701700/Ports.nr.2.zip)

**Comment by infokujur** [comment]
Novembris lisasin ise otse kausta - kas see oli ok? Kui jah, siis paneme teema kinni. Kui mitte, siis postitan ilusti järgmine kord paki jälle siia.

**Comment by tkutsar** [comment]
See oli igati ok
