### ISSUE TITLE
Joonis 1.3.1

### ISSUE THREAD

**Issue by EgleAdams** [Demokraatialabor/EIA_2019#70]
Joonisega 1.3.1 mingi kala vist, seda saab liigutada, aga alt viimased aastanumbrid üksteise otsas ja pole eristatavad.

**Comment by tkutsar** [comment]
See oli testimiseks üleval. Praegu tehtud uuesti staatiliseks, aga jätan issue lahti, kuniks interaktiivne versioon on tööle saadud.

**Comment by tkutsar** [comment]
Parandatud
