### ISSUE TITLE
Tabel 0.1 font - sama suureks kui tabel 0.2

### ISSUE THREAD

**Issue by Anni-M** [Demokraatialabor/EIA_2019#75]

**Comment by tkutsar** [comment]
Kas saad täpsustada? Fontide suurus on Tabelitel 0.1 ja 0.2 sama.

**Comment by Anni-M** [comment]
Praegu ei ole inimareng. ee üleval, muidu teeks pilti. Veebi vaates olid sissejuhatuste tabeli pealkirjad erinevates suurustes. Tabel 0.2 sama suur kui joonistel, tabel 0.1 väiksem

**Comment by Anni-M** [comment]
![1](https://user-images.githubusercontent.com/61053130/83978472-5fcc0b00-a910-11ea-88b7-8fdee44d6b5b.PNG)
![2](https://user-images.githubusercontent.com/61053130/83978473-62c6fb80-a910-11ea-8af5-ed6fdfa38b78.PNG)

**Comment by tkutsar** [comment]
Parandatud
