### ISSUE TITLE
Artiklis 2.1 tsitaat unbold ja italicus

### ISSUE THREAD

**Issue by Anni-M** [Demokraatialabor/EIA_2019#76]
Tekst:

„Õigusaktides tuleb luua senisest selgemad alused ruumiloomele tervikuna, haarates seostatuna kõiki ruumiotsuseid. Seaduses tuleb seostatult käsitleda ruumiloome põhimõtteid ja mõisteid. Avaliku ruumi olulisuse rõhutamine ruumiloomes ja kvaliteedinõude sõnastamine annavad parema aluse kvaliteetse avaliku ruumi ja ehitatud keskkonna rajamiseks ning eelnõude ruumimõju hindamiseks.“

Samamoodi teha nagu sissejuhatuse alguses on Lennart Meri tsitaat

**Comment by tkutsar** [comment]
Tehtud
