### ISSUE TITLE
Eessõnas - presidendi foto teksti lõppu

### ISSUE THREAD

**Issue by Anni-M** [Demokraatialabor/EIA_2019#78]
Mobiilivaates on totakas, et kohe suurelt tuleb presidendi näofoto, see palun panna lõppu

**Comment by tkutsar** [comment]
Kas desktopi vaates peaks jääma samale kohale, kus praegu? Kas pilt peaks olema kõige lõpus või enne tiitlit?

**Comment by Anni-M** [comment]
Desktop vaates võib ka liikuda, pigem kõige lõpus

**Comment by tkutsar** [comment]
Tehtud
