### ISSUE TITLE
Järgmise artikli avamine mobiilis

### ISSUE THREAD

**Issue by Anni-M** [Demokraatialabor/EIA_2019#79]
Hetkel on noolekene ainult teksti lõpus, kas see võiks olla ka teksti alguses. Nt kui tahad vahele jätta mõnda teksti, siis ei peaks tingimata lõpuni scrollima.

**Comment by tkutsar** [comment]
See on bookdowni funktsionaalsus, ümbertegemine pole mahu piires. Artiklite vahel navigeerimiseks saab ka kasutada menüüd.
