### ISSUE TITLE
Kolmerealised sissejuhatuse pealkirjad jäävad mobiilis nuppude alla natuke

### ISSUE THREAD

**Issue by Anni-M** [Demokraatialabor/EIA_2019#83]
![unnamed (2)](https://user-images.githubusercontent.com/61053130/83972058-e4099880-a8e6-11ea-9dcf-b046c4a656bc.jpg)

**Comment by tkutsar** [comment]
Parandan juba olemasoleva issue raames: https://github.com/Demokraatialabor/EIA_2019/issues/73
