### ISSUE TITLE
Mobiilis on menüü liiga lai

### ISSUE THREAD

**Issue by Anni-M** [Demokraatialabor/EIA_2019#84]
Kõrvalolev tekst jääb väga kitsalt ribale. 
![unnamed (3)](https://user-images.githubusercontent.com/61053130/83972118-2206bc80-a8e7-11ea-826e-257fa78e6c72.jpg)

**Comment by tkutsar** [comment]
Bookdowni funktsionaalsus, parandamine ei ole mahu piires. Lai ekraani kattev "hamburgermenüü" on mobiilivaadete puhul tavaline praktika. Jääb parandamata.
