### ISSUE TITLE
Mobiilis "search" funktsiooni kasutades nihkub vaade

### ISSUE THREAD

**Issue by Anni-M** [Demokraatialabor/EIA_2019#86]
Ekraanivaade nihkub nii, et ma ei näe seda mida trükin
![unnamed (6)](https://user-images.githubusercontent.com/61053130/83972320-241d4b00-a8e8-11ea-93f7-cf870736bd33.jpg)
![unnamed (4)](https://user-images.githubusercontent.com/61053130/83972322-28496880-a8e8-11ea-9cbd-8be104fbb34b.jpg)
![unnamed (5)](https://user-images.githubusercontent.com/61053130/83972328-2c758600-a8e8-11ea-8420-bc645be5551d.jpg)

**Comment by tkutsar** [comment]
Tegemist on Bookdowni veaga. Selle parandamine ei ole mahu piires ja seega jääb tegemata.

Ebamugavam, aga ei ole kriitilise tähtsusega.
