### ISSUE TITLE
Mobiilis autori nimele klikates viskab vaate, kus ei ole autorit nime ega pilti vaid esimene kirjelduse lause

### ISSUE THREAD

**Issue by Anni-M** [Demokraatialabor/EIA_2019#87]
Ta peaks viskama nii, et on näha nime ning selle all on foto ja siis tuleb kirjelduse tekst

**Comment by tkutsar** [comment]
Tehnilistel põhjustel lahendatud nii, et viskab pildi, siis nime, siis teksti. Aga kõik kolm elementi nüüd nähtavad.
