### ISSUE TITLE
Väljatõste puudu 1.1 Kokkuvõte

### ISSUE THREAD

**Issue by infokujur** [Demokraatialabor/EIA_2019#91]
https://inimareng.ee/maakasutuse-muutused-linna-ja-maa-t%C3%A4henduse-moondumine.html

Väärtusliku põllumaa püsimine on oluline nii Eesti julgeoleku kui ka meie traditsiooniliste tegevusalade ja kultuuri säilimise seisukohalt. Samuti vähendab metsade vanusstruktuuri muutus elurikkust meie looduses.

**Comment by tkutsar** [comment]
Lisatud
