### ISSUE TITLE
Väljatõste puudu 1.2 Ääremaastaatus ja -kuvand piiravad koha konkurentsivõime kasvu

### ISSUE THREAD

**Issue by infokujur** [Demokraatialabor/EIA_2019#92]
https://inimareng.ee/keskuse-ja-%C3%A4%C3%A4remaa-l%C3%B5he-eestis.html#%C3%A4%C3%A4remaastaatus-ja--kuvand-piiravad-koha-konkurentsiv%C3%B5ime-kasvu

Kuvandi ümberpööramisel kasutatakse ääremaisust „trumpkaardina“. Nii väidavad
kohalikud otsustajad näiteks Kihnus ja Setomaal, et just ääremaastaatus on võimaldanud neil maaelu idülli ja kultuurilist pärandit säilitada.

**Comment by tkutsar** [comment]
Lisatud
